### ISSUE TITLE
x3daudio1_7_hrtf download page broken

### ISSUE THREAD

**Issue by gbr000** [ThreeDeeJay/x3daudio1_7_hrtf#1]
The page `https://github.com/kosumosu/x3daudio1_7_hrtf/releases` is broken, 

maybe for days!? Even for years?

**Comment by gbr000** [comment]
Thanks! Now I got it. How can I know all the games that support it? Is there a list? I assume you must download 64 bit for 64 games and 32 bit for the 32 bit. Cheers!

**Comment by ThreeDeeJay** [comment]
Here's a list of known games that do or *might* potentially work: https://kutt.it/BinauralProfilesX3DAudio
The list isn't that big, so you also might wanna check out the full database to see if there are other methods to get 3D or at least surround sound:

Database (configuration guides, demos, ratings, etc.)
📇https://kutt.it/BinauralInterface                     Search and navigate database links. Requires (free) account, but trust me, it's worth it
📃https://kutt.it/BinauralDatabase                    Spreadsheet sorted A-Z
📅https://kutt.it/BinauralDatabaseRecent      Spreadsheet sorted by most recently added
📰https://kutt.it/BinauralDatabaseCatalog     Search by configuration profile (Click Go to record. ☑️ Best known one will be the first result. Slow)
🔍https://kutt.it/BinauralDatabaseSearch       Search by title
📝https://kutt.it/BinauralDatabaseAdd            Form to submit new games/apps
